### ISSUE TITLE
Setup finished, but Parsec only displays a black screen (with parsec icon top left)

### ISSUE THREAD

**Issue by nirurin** [parsec-cloud/Parsec-Cloud-Preparation-Tool#37]
Google Cloud server, running a T4 Tesla, all the drivers got installed by your script and a final restart happened. In the device manager, two monitors are listed so I have disabled the GGA one, keeping the T4 monitor there. But Parsec doesn't seem to want to pick it up? The Parsec monitor is listed as "\\.\display1", and it's the only display listed.

**Comment by jaylfc** [comment]
Same here, rolling back the driver fixes it but can't play new games like COD Warzone due to driver error crashing.

**Comment by alexmcco** [comment]
@jaylfc I'm having the same issue. Would you mind linking to the drivers you've got working?

**Comment by abazlinton** [comment]
Try Windows-Shift-Left-Arrow and Windows-Shift-Right-Arrow

It moves a window between screens

**Comment by alexmcco** [comment]
@abazlinton Thank you. I can't test if that worked because today I blew away my instance and tried again with the tool—this time the tool told me I was already all up to date and everything has been working perfectly. 🤷🏻‍♂️

**Comment by diegosucaria** [comment]
I fixed it by installing the driver from here: 
https://cloud.google.com/compute/docs/gpus/grid-drivers-table

This it the link I used: https://storage.googleapis.com/nvidia-drivers-us-public/GRID/GRID11.0/451.48_grid_win10_server2016_server2019_64bit_international.exe

**Comment by patriciodavila** [comment]
Not sure if this is the same problem but after everything is installed (no errors) and restarted, logging in through Parsec gives me two issues: screen aspect ratio looks squeezed with black bars showing on left and right; no windows show (even though they show in RDP), but task bar, Parsec button, and mouse shows. No error messages at any point. The setup is GCP with P4.

**Comment by jamesstringerparsec** [comment]
If you connect to a desktop where you see a task bar, the Parsec logo on the desktop and you click on items on the task bar and nothing happens, it means the cloud machine has the primary display set to a display Parsec can't capture.

In this situation, you should do the following:

1) Connect to the host via Parssec
2) Press CTRL + Shift + i (this will enter into immersive mode)
3) Press Windows Key + P
4) Press Down Arrow, Down Arrow, Enter.

This will change the display arrangement to only output to the secondary monitor which is probably the one you are looking at.

**Comment by jamesstringerparsec** [comment]
If the screen is completely black, but you can see the mouse cursor when you move the mouse around (may take you a while to find it) then your computer is at a lock screen, but the lock screen is showing on a screen Parsec can't capture.  All other screens on the lock screen are always showing as completely black.  This is what Parsec is capturing.

**Comment by jamesstringerparsec** [comment]
Generally the solution to all your problems is to NEVER use the option to add a Display Device on Google Cloud.

If you have already done that...you're going to need to delete the instance and start again.
![image](https://user-images.githubusercontent.com/38541878/102884304-b2ef5080-4451-11eb-99fe-13c1d8b86562.png)

**Comment by patriciodavila** [comment]
i suspected the "display device" setting might do something to mess things up; i'll try the other recommendations too

**Comment by mattmac24** [comment]
I am having this issue on AWS windows server 2019. How can I solve this?

**Comment by jamesstringerparsec** [comment]
@mattmac24 Please read the previous comments where I outlined the solutions.

If the solutions do not work, please be more descriptive with how you set up the instance, including operating system, options you selected when configuring the instance in AWS, as well as the options you selected inside the Cloud Prep Tool.

**Comment by mattmac24** [comment]
@jamesstringerparsec thanks for the reply. It could be that the above solutions do not work for me because I am using a mac laptop/ keyboard and am not 100% sure I am sending the right commands to the server through Parsec. None of the above commands seem to register anything.
I followed this youtube video: https://www.youtube.com/watch?v=H3vP6hD3fRo

- I am using Microsoft Windows Server 2019 Base - ami-01b65a06ec09db85c
- Location: Frankfurt EU-central-1
- I would like to use g4dn.2xlarge but I have also tried with g4dn.large & g4dn.4xlarge with the exact same issue.
- In the AWS instance configurator I am leaving everything default except increasing the size of the root gp2 volume to 512gb.
- I entered all 'Y' in the cloud prep tool and did login with Razor to be sure.
- Running the GPU updater script from the desktop afterwards tells me that I am up to date.
- I also tried with Windows Server 2016 base, but the powershell command gave an error and I switched back to Server 2019 to continue trying(Microsoft Flight Simulator 2020 needs windows 10 or server 2019 I believe anyway which is what I am trying to play) .
- I must have rebuilt the instance 5 or 6 times now, the only thing I can see that I am doing differently from the Youtube video is the server location, so I am now thinking to try from Paris instead of Frankfurt.
- I do notice that when I first connect there is a blue big vertical bar on the right side of the screen that tells me Windows was unable to Project to the screen. I am not sure what this means but I think it has to be related to my issue.

Hope I included all the relevant details!
