### ISSUE TITLE
Error code 6025

### ISSUE THREAD

**Issue by shouari** [parsec-cloud/Parsec-Cloud-Preparation-Tool#60]
Hello, I followed all steps on AWS windows 2019 but at the end I got error 6025?
![image](https://user-images.githubusercontent.com/42525079/103177721-dc630e80-488d-11eb-9ec8-a16a68fdb853.png)

**Comment by jamesstringerparsec** [comment]
Hi 

This github repo isn't for discussing issues with Parsec, but your profile says you're in the middle east.  This is likely due to your government or a workplace tampering with your connection (eg some kind of network traffic inspection or firewall).  Most middle eastern Arabic counties are now rolling out these type of protections at a country level that block the Parsec application.
